{% set component_name = "gui" %}
{% set base_name = "libignition-" + component_name %}
{% set version = "6_6.8.0" %}
{% set version_package = version.split('_')[1] %}
{% set major_version = version_package.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version_package }}

source:
  - url: https://github.com/gazebosim/gz-{{ component_name }}/archive/ignition-{{ component_name }}{{ version }}.tar.gz
    sha256: bd5428b1ee8b7eb0e69ab6d5abe02a57afc9ecc56e76dd9a7f251bb7d2baa04a
    patches:
      - fixprotobuf.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - cmake
    - pkg-config
  host:
    - libignition-cmake2
    - libprotobuf
    - tinyxml2
    - libignition-math6
    - libignition-common4
    - libignition-plugin1
    - libignition-transport11
    - libignition-rendering6 >=6.6
    - libignition-msgs8
    - libignition-tools1
    - libignition-utils1
    - qt-main
    - xorg-libxfixes  # [linux]
    - libgl-devel  # [linux]
    - ogre 1.10.*
  run:

test:
  commands:
    - test -f ${PREFIX}/include/ignition/{{ component_name }}{{ major_version }}/ignition/{{ component_name }}.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-{{ component_name }}{{ major_version }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-{{ component_name }}{{ major_version }}/ignition-{{ component_name }}{{ major_version }}-config.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\\{{ component_name }}{{ major_version }}\\ignition\\{{ component_name }}.hh exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\ignition-{{ component_name }}{{ major_version }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\ignition-{{ component_name }}{{ major_version }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-{{ component_name }}{{ major_version }}\\ignition-{{ component_name }}{{ major_version }}-config.cmake exit 1  # [win]

about:
  home: https://github.com/gazebosim/gz-{{ component_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Robotics library that builds on top of Qt to provide widgets which are useful when developing robotics applications, such as a 3D view, plots, dashboard.
extra:
  feedstock-name: {{ base_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
    - j-rivero
